config/routes.rb
Bookmarks::Application.routes.draw do
  get 'users/index'

  get 'welcome/index'

  get 'welcome/about'

  devise_for :users
  
  root to: 'welcome#index'

 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Bookmarks", root_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
   </ul>

<%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Bookmarks</h1>
<p>Created by: Chéri</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bookmarks</h1>
<p>This is the home page for Bookmarks</p>